name: Daily Betting Algo

on:
  schedule:
    - cron: '0 7 * * *' # Tourne tous les jours à 07h00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Algorithm
        env:
          API_KEY: ${{ secrets.API_FOOTBALL_KEY }}
        run: python main.py

      - name: Commit and Push Data
        run: |
          git config --global user.name 'GitHub Action Bot'
          git config --global user.email 'action@github.com'
          
          # 1. On ajoute et on commit D'ABORD les fichiers générés
          # Cela "protège" le travail du robot avant de tenter la mise à jour
          git add data_cache/ predictions_anj.json
          git commit -m "Auto-update: Predictions & Cache" || echo "Rien à commiter"
          
          # 2. MAINTENANT on peut récupérer tes modifications (ton main.py)
          # Le --rebase va placer le commit du robot juste APRES tes modifications
          git pull origin main --rebase
          
          # 3. On envoie le tout
          git push
