name: Daily Betting Algo

on:
  schedule:
    - cron: '0 7 * * *' # 07h00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Algorithm
        env:
          API_KEY: ${{ secrets.API_FOOTBALL_KEY }}
        run: python main.py

      - name: Commit and Push Data
        run: |
          git config --global user.name 'GitHub Action Bot'
          git config --global user.email 'action@github.com'
          
          # Force l'ajout du cache (même si ignoré) et du BON fichier json
          git add -f data_cache/
          git add predictions_top5.json
          
          # Commit (évite l'erreur si rien n'a changé avec allow-empty)
          git commit -m "Auto-update: Predictions & Cache" || echo "Rien à commiter"
          
          git pull origin main --rebase
          git push
