name: Daily Betting Algo

on:
  schedule:
    - cron: '0 7 * * *' # Tourne tous les jours à 07h00 UTC (08h00 France)
  workflow_dispatch: # Permet de lancer manuellement le bouton "Run workflow"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Important pour pouvoir sauvegarder les fichiers

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Algorithm
        env:
          API_KEY: ${{ secrets.API_FOOTBALL_KEY }} # Ta clé secrète GitHub
        run: python main.py

      - name: Commit and Push Data
        run: |
          git config --global user.name 'GitHub Action Bot'
          git config --global user.email 'action@github.com'
          
          # --- CORRECTION DU CONFLIT ---
          # On récupère d'abord les changements distants (ton main.py modifié)
          # L'option --rebase permet d'appliquer tes changements proprement
          git pull origin main --rebase
          
          # Ensuite on ajoute les nouveaux fichiers générés
          git add data_cache/ predictions_anj.json
          
          # On commit et on push (le || exit 0 évite de planter s'il n'y a rien de nouveau)
          git commit -m "Auto-update: Predictions & Cache" || exit 0
          git push
